spring.application.name=TwoDBSpringBootConfig
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#   === Company DB - SQL =====

spring.datasource.company.jdbc-url=jdbc:mysql://localhost:3306/eazybank
spring.datasource.company.username=root
spring.datasource.company.password=admin123
spring.datasource.company.driver-class-name=com.mysql.cj.jdbc.Driver

#   === Client DB - SQL =====

spring.datasource.client.jdbc-url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.client.username=shanthi
spring.datasource.client.password=admin
spring.datasource.client.driver-class-name=oracle.jdbc.OracleDriver



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.tool.hbm2ddl=DEBUG