spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/shanthipillai/Config.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.search-paths=.

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Config Auto Bus
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=busrefresh,refresh,monitor
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.refresh-rate=0


spring.profiles.active=git