spring.application.name=card-service
server.port=8081

#   === Client DB - ORACLE =====

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=shanthi
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update