spring.application.name=SpringEntityManager

#Spring DB configuration 
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Hibernate statistics
spring.jpa.properties.hibernate.generate_statistics=true

logging.level.org.hibernate.stat=DEBUG
logging.level.org.hibernate.orm.stat=DEBUG
logging.level.org.hibernate.engine.internal.StatisticalLoggingSessionEventListener=DEBUG
spring.jpa.properties.hibernate.session.events.log.LOG_SESSION_METRICS=true
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
