spring.application.name=account-service
server.port=8080
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev
management.endpoints.web.exposure.include=refresh,busrefresh
#MQ bus
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#management.endpoints.web.exposure.include=busrefresh

# Default config for all circuit breakers
resilience4j.circuitbreaker.configs.default.slidingWindowSize=3
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=3
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s

#spring.cloud.openfeign.client.config.default.retryer=feign.Retryer$NeverRetry