spring.application.name=EurekaServer
server.port=8557

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8557/eureka/
eureka.server.enable-self-preservation=false